###
# GET ALL CLIENTS
GET http://localhost:3000/
###
# GET ONE CLIEN BY ID
GET http://localhost:3000/95d0658f-9cfd-47be-b6d9-e92b01f89587
###

###
# POST new form
POST http://localhost:3000/
Content-Type: application/json


{
    "formname": "alo",
    "description": "Segundo",
    "formdata":{
        "1":{"name":"User", "type": "text"}

    }
}
###

###
# POST create table
POST http://localhost:3000/createTableForms
Content-Type: application/json

{
    "dni": "53702804n"
}
###

###
# DELETE form by id
DELETE   http://localhost:3000/6cb12cd8-331b-477e-8f7b-ce69ff21f4ca
Content-Type: application/json


###

###
# PUT update form by id
PUT http://localhost:3000/3b9cb414-b222-4a68-b09c-2afad9c2d845
Content-Type: application/json

{

    "description": "Almacen trasero delantero"
        
    
}
###

###
###

###